package net.zjvis.flint.data.hub.controller.algorithm.vo;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.*;
import lombok.extern.jackson.Jacksonized;
import net.zjvis.flint.data.hub.controller.artifact.vo.BusinessDockerRegistryImageVO;

@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
@Getter
@Setter
@Jacksonized
@EqualsAndHashCode
@ToString
@Schema
public class AlgorithmVO {
    @Schema(description = "Generated by database to identify unique algorithm")
    private Long id;
    @Schema(description = "Values config info with yaml format")
    private String valuesYaml;
    @Schema(description = "Algorithm input parameter template with yaml format")
    private String configurationYaml;
    @Schema(description = "Algorithm (input/output) parameter template with yaml format")
    private String paramInfoTemplateYaml;
    @Schema(description = "Algorithm service image registry")
    private String registry;
    @Schema(description = "Algorithm base image info")
    private BusinessDockerRegistryImageVO baseImage;
    @Schema(description = "Algorithm file directory")
    private String dirPath;
}
