package net.zjvis.flint.data.hub.controller.algorithm.vo;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.datatype.jsr310.deser.LocalDateTimeDeserializer;
import com.fasterxml.jackson.datatype.jsr310.ser.LocalDateTimeSerializer;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.*;
import lombok.extern.jackson.Jacksonized;
import net.zjvis.flint.data.hub.util.ActionStatusEnum;

import java.time.LocalDateTime;

@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
@Getter
@Setter
@Jacksonized
@EqualsAndHashCode
@ToString
@Schema
public class AlgorithmDeployVO {
    @Schema(description = "Generated by database to identify unique algorithm deploy")
    private Long id;
    @Schema(description = "Algorithm release/deploy/use info")
    private AlgorithmVO algorithmVO;
    @Schema(description = "Algorithm deploy status", example = "CREATED , RUNNING , FAILED , SUCCEED , CANCELED")
    private ActionStatusEnum status;
    @Schema(description = "Algorithm deploy values info")
    private String valuesContent;
    @Schema(description = "Algorithm deploy job name")
    private String jobName;
    @Schema(description = "Algorithm deploy job start time")
    @JsonDeserialize(using = LocalDateTimeDeserializer.class)
    @JsonSerialize(using = LocalDateTimeSerializer.class)
    private LocalDateTime gmtCreate;
    @Schema(description = "Algorithm deploy job updated time")
    @JsonDeserialize(using = LocalDateTimeDeserializer.class)
    @JsonSerialize(using = LocalDateTimeSerializer.class)
    private LocalDateTime gmtModify;
}
