apiVersion: batch/v1
kind: Job
metadata:
  name: algorithm-builder
  labels:
    app.kubernetes.io/name: algorithm-builder
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: algorithm-builder
    spec:
      initContainers:
        - name: fetch-resource
          image: docker.io/bitnami/minio-client:2022.8.11-debian-11-r3
          imagePullPolicy: IfNotPresent
          env:
            - name: MINIO_ENDPOINT
              value: "http://host.docker.internal:9000"
            - name: MINIO_ACCESSKEY
              value: "minioadmin"
            - name: MINIO_ACCESSSECRET
              value: "minioadmin"
            - name: ALGORITHM_BUCKET
              value: "algorithms"
            - name: ALGORITHM_OBJECT_KEY
              value: "algorithm.tar.gz"
          command:
            - "/bin/bash"
          args:
            - "-c"
            - "/app/bin/build-init.sh"
          volumeMounts:
            - mountPath: /app
              name: nebula-algorithm
            - mountPath: /app/bin
              name: nebula-algorithm-init
      containers:
        - name: dockerd
          image: docker.io/docker:20.10.23-dind-alpine3.17
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/lib/docker
              name: dind-storage
            - mountPath: /var/run
              name: dind-socket
        - name: algorithm-builder
          image: docker.io/docker:20.10.23-cli-alpine3.17
          imagePullPolicy: IfNotPresent
          workingDir: /app
          env:
            - name: DOCKER_REGISTRY
              value: "docker-registry-ops-dev.lab.zjvis.net:32443"
            - name: BASE_PYTHON_REGISTRY
              value: "docker.io"
            - name: BASE_PYTHON_IMAGE
              value: "python"
            - name: BASE_PYTHON_TAG
              value: "3.9.14-bullseye"
            - name: ALGORITHM_NAME
              value: "algorithm-demo"
            - name: ALGORITHM_VERSION
              value: "2022.11.18-r0"
            - name: CALLBACK_ADDRESS
              value: "http://10.105.20.64:32086/server/algorithm/v1/callback"
            - name: CALLBACK_TOKEN
              value: "82b1143a0fd32db03749504176b1bf51"
          command:
            - "/app/bin/builder.sh"
          volumeMounts:
            - mountPath: /var/lib/docker
              name: dind-storage
            - mountPath: /var/run
              name: dind-socket
            - mountPath: /app/bin
              name: nebula-algorithm-init
            - mountPath: /app
              name: nebula-algorithm
      volumes:
        - name: dind-storage
          emptyDir: { }
        - name: dind-socket
          emptyDir: { }
        - name: nebula-algorithm
          emptyDir: { }
        - name: nebula-algorithm-init
          configMap:
            defaultMode: 493
            name: nebula-algorithm-configmap
      shareProcessNamespace: true
      restartPolicy: OnFailure
